# Generated by Django 2.2.dev20181217100344 on 2018-12-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit_hold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('circuit', models.BinaryField(max_length=1000)),
                ('components', models.BinaryField(default=None, max_length=1000)),
                ('lastID', models.IntegerField(default=0)),
            ],
        ),
    ]
