# Generated by Django 2.2.dev20181217100344 on 2018-12-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit_hold',
            name='components',
            field=models.BinaryField(max_length=1000, null=True),
        ),
    ]
