# Generated by Django 2.1.4 on 2018-12-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit_app', '0003_circuit_hold_input_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit_hold',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
